#!/usr/bin/env node
require.paths.push(__dirname + '/lib');
require.paths.push(__dirname + '/etc');
require("coffee-script");

process.title = "dzbugs";

var DZ = {}; global.DZ = DZ;

DZ.term = require("node-term-ui"),
DZ.log = require("notifications.js").log;
DZ.error = require("notifications.js").error;
DZ.formater = require("format.js");
DZ.conf = require("conf.js");
DZ.sorters = require("sorters.js");
DZ.keys = require("keys.js");
DZ.layout = require("layout.js");
DZ.commandLine = require("commandline.js");
DZ.commands = require("commands.js");
DZ.bz = require("bugzilla.js");
DZ.store = require("bugstore.js");
